/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.appkim.i18nstrings.plugin

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

import kotlinx.coroutines.test.runTest

/**
 * A simple functional test for the 'com.appkim.i18nstrings.plugin' plugin.
 */
@OptIn(ExperimentalStdlibApi::class)
class I18nStringsPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }


    //This method is mainly used to test the version compatibility of the gradle plugin by setting different gradle versions. The lowest supported gradle version found is 7.4
    @Test fun `can run task`() = runTest {
    // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('com.appkim.i18nstrings')
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.withGradleVersion("7.4") //Setting the gradle version
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("i18nStrings")
        runner.withProjectDir(projectDir)
        val result = runner.build()


        // Verify the result
        assertTrue(result.output.contains("hello world"))
    }

}
